aList=['FirstName','LastName',"Guido","Rossum",10,20]
print(aList,type(aList))
a=tuple(aList)
print(a,type(a))
abc=('FirstName','LastName',"Guido","Rossum",10,20)
c=list(abc)
print(list(c),type(c))
int()
str()